name: Comment to Commit using Aider

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  generate:
    if: ${{ contains(github.event.comment.body, '@aider') }}
    uses: oscoreio/ai-workflows/.github/workflows/comment-to-commit-using-aider.yml@main
    with:
      comment-id: ${{ github.event.comment.id }}
      pr-url: ${{ github.event.issue.pull_request.url || github.event.pull_request.url }}
    secrets:
      # You need set one of these keys
      openrouter-api-key: ${{ secrets.OPENROUTER_API_KEY }} # while it allows to use DeepSeek R1 for free, it still required to rate-limiting you
      openai-api-key: ${{ secrets.OPENAI_API_KEY }}
      anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
      groq-api-key: ${{ secrets.GROQ_API_KEY }}
      gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
      cohere-api-key: ${{ secrets.COHERE_API_KEY }}
      deepseek-api-key: ${{ secrets.DEEPSEEK_API_KEY }}
